apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: premteam-replicaset
  namespeace: cloud-explorer-d
  labels: 
    app: premteams
    tier: backend
spec:
  selector:
    matchLabels: 
      app: premteams
  replicas: 3
  template:
    metadata: 
      name: premteam
      labels: 
        app: premteams
    spec:
      containers:
        - name: teams
          image: premanshu/teamsresources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100m"
