apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-headless
  namespace: cloud-explorer-d
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017