---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: cloud-explorer-d
spec:
  serviceName: "mongo-svc"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo
          command:
            - /bin/sh
            - -c
            - >
              mongod --replSet rs0 --bind_ip 0.0.0.0;
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: callcenterdb
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: callcenterdb
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi