name: test Azure login and others
on:
  workflow_dispatch
env:
  SERVICES_PATH: "./src/services"
jobs:
  AzureLogin:
    name: "AzureLogin"
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v1
        with:
          creds: '{"clientId":"1c36ea3b-2887-4d9c-ab27-13f7a82a7d3f","clientSecret":"sSc8Q~UeHx.X4hoNsx3I0pzxgnwX92xybXdqSa~D","subscriptionId":"641cc733-cfeb-4c4c-bdc5-a126d7cc22f4","tenantId":"05d75c05-fa1a-42e7-9cf1-eb416c396f2d"}'
          
